### ISSUE TITLE
Top bar monitor shifting and other compatibility issues

### ISSUE THREAD

**Issue by wuqso** [neuromorph/openbar#22]
1. Setting 'Top' for 'Position of Bar' will move the top bar to the top of the external display if the external display is set to be above the built-in display with system display settings. Also, the system display settings make the build-in display to be the primary display with top bar and activities.
2. After all other extensions are disabled, the bottom of the date panel (Events, world clocks, and weather) will be cut after a screen lock.

My system is Fedora 40 workstation edition prerelease version and Gnome 46.

**Comment by neuromorph** [comment]
Hello wuqso, Thank you for reporting!
I assume you are using the latest version released for Open Bar. I will address these issues below:

1. Top bar monitor: In the released version, Open Bar assumes Top Bar to be on Primary monitor and sets it so when choosing position Top/Bottom or during Activities overview. This assumption breaks when another extension changes the monitor for Top bar ([this issue](https://github.com/neuromorph/openbar/issues/20#issue-2193240267)). So, now I've changed Open Bar to not set any monitor at all. Instead, it checks which monitor the bar is on and just moves it to Top or Bottom on the same. This update is available in Github, I will provide command to get it at the bottom below. Note: I noticed that, if an extension moves the top bar to another monitor and if you disconnect the monitor and disable the extension, after reconnecting the monitor, the bar might move to it again. If so, rearrange the monitors to a different layout in System settings and hit Apply, then the bar should move back to Primary. Now you can change monitor layout as desired.
2. This is a compatibility issue with Lunar Calendar. Note that, once the issue happens it will persist even if you disable Lunar, until you reload Gnome. This issue along with the ones you mentioned on the Extensions web pages for Open Bar and Lunar Calendar are all compatibility issues with Lunar. They should also be fixed with the update in Github. Please refer[ this issue](https://github.com/neuromorph/openbar/issues/21#issue-2201928259) for more updates.

Run the command below to get the update from Github:
`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/extension.js; cd` 

The fixes will be released in the next update for Open Bar. Meanwhile, you can get them with above command. If you still encounter some issue, feel free to report here.

**Comment by wuqso** [comment]
Thank you very much for your reply. Unfortunately, I have no access to the website you mentioned. I'll wait for the next update of open bar. It's really an amazing extension.

**Comment by neuromorph** [comment]
> Unfortunately, I have no access to the website you mentioned. I'll wait for the next update of open bar

I will let you know here once the update is released. Meanwhile, you don't need to access any website, simply run following command in a terminal to get the update now. After that you will need to logout and log back in.
`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/extension.js; cd`

> It's really an amazing extension.

Thanks a lot :)

**Comment by wuqso** [comment]
Yes, I just run the command in a terminal and get the update. But the problem remains...

**Comment by neuromorph** [comment]
> Yes, I just run the command in a terminal and get the update. But the problem remains...

Which of the issues still remain? You will need to provide me more details to help me see and fix the issue. What other extensions do you have and how to reproduce the issue?
Run the following command in terminal to monitor errors. Then reproduce the issue. Now check in terminal for any errors/warnings and paste it here. 
` journalctl /usr/bin/{gjs,gnome-shell} -fo cat`

**Comment by wuqso** [comment]
The top bar is still on top of the external monitor. The second problem disappears after a system update.

I have 'Alphabetical App Grid', 'Astra Monitor', 'Clipboard History', 'Lunar Calendar', 'Screen word translate', 'Wallpaper Slideshow', and 'Weather O'clock' installed.

The errors/warnings are

Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
lunarcal: using backend ytliu0
section added:  LunarCalendarSection
Failed to create new MetaSelectionSourceMemory: Failed to create MetaAnonymousFile
Failed to create new MetaSelectionSourceMemory: Failed to create MetaAnonymousFile
GNOME Shell started at Tue Mar 26 2024 14:22:54 GMT+0800 (China Standard Time)
Registering session with GDM
Shutting down GNOME Shell
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed

after running the command you suggested.

**Comment by wuqso** [comment]
It's funny that the top bar will move to the top of the built-in monitor after I change the connection to the external monitor from the left USB interface of my laptop to the right one.

**Comment by neuromorph** [comment]
> The top bar is still on top of the external monitor. The second problem disappears after a system update.

Good to hear that the second issue is resolved. About bar being on external monitor, well, Open Bar checks where it is and retains the monitor so it should be something else causing it most likely. 
I am yet to get a chance to double-check with an external monitor but I did test earlier and the result was as I had explained earlier. To reiterate, your system may remember some configuration if you use same monitor and connect on same port etc. If something had pushed the Top bar to external monitor earlier, then it may remember it. In my case, FullScreen Avoider extension had pushed the bar to another monitor and it remained even after disabling extension, disconnecting monitor and then reconnecting it. I was able to fix it by going into Display settings, change layout of monitors and apply.

> The errors/warnings are

This log does not suggest any errors to cause the issue so it seems fine.

> It's funny that the top bar will move to the top of the built-in monitor after I change the connection to the external monitor from the left USB interface of my laptop to the right one.

Yes, it changes the configuration so. Please try with your original configuration but change layout and/or Primary/Secondary monitor in Display settings and that should reset it. Then you can set the configuration again as desired.

**Comment by wuqso** [comment]
I have never installed FullScreen Avoider extension. Disconnecting monitor and reconnecting it do not fix my problem.

**Comment by neuromorph** [comment]
> Please try with your original configuration but change monitors layout and/or Primary/Secondary monitor in **Display settings** and that should reset it. Then you can set the configuration again as desired.

**Comment by wuqso** [comment]
Unfortunately, it does not solve my problem. I once deleted the monitors.xml and monitors.xml~ in .config and configure the display layout again, but the problem remained there.
Thank you very much for your help! I can use the right USB port to connect the external monitor.

**Comment by neuromorph** [comment]
The Open Bar compatibility update for Lunar as well as update for monitors is now live! Closing this.
