### ISSUE TITLE
It moves the top panel to the second screen

### ISSUE THREAD

**Issue by GovenorKratos** [neuromorph/openbar#30]
Whenver I enable the extension, it moves the top bar to the second display. 

I'm not sure if it's an Nvidia issue or if I'm just unlucky to have a laptop with 2 graphics that I can't switch between. The HDMI is connected to the dGPU directly and the iGPU is connected to the laptop display. (not sure if this is helpful, just mentioning if anyone tries recreating). 

I can't use the extension without it jumping the entire top bar over to the second display. This makes my dock on the primary display and the top bar on the non primary display.

**Comment by neuromorph** [comment]
Open Bar tries to keep the panel on the monitor that it is found to be on. This is since some extensions allow moving the panel to other monitors. However, I found a bug that made it dependent on the connections and layout of the multi-monitors, that most likely caused this issue.
I have fixed it and uploaded to GitHub. NOTE: It is only available in 'main' branch which is for Gnome 45+ (I will backport it later). I assume you are also on Gnome 45/46. It would be great if you manually install it from GitHub.
Since I have also added few other fixes for other issues you will be getting those as well. You can clone the repo and replace the local installation directory with it OR you can download and replace the following at least:
- schemas/ (both files in the directory)
- extension.js
- stylesheets.js
- prefs.js

Let me know how it goes.

Thank you for reporting!

**Comment by neuromorph** [comment]
The fix is now part of the live version published in E.G.O. (Gnome Extensions web), so closing this issue.

**Comment by RVFET** [comment]
@neuromorph 

This issue still persists. I just downloaded it on my Fedora 41 / Gnome 47 with two monitors and the laptop's own monitor. OpenBar ignores the "Primary Display" option that I've set on gnome settings/display and forces the top bar to appear only on the laptop's screen, which is not the desired outcome. Current state of the extension is sadly unusable for me, since my setup is not laptop-screen centric.

![Image](https://github.com/user-attachments/assets/8f615349-7c69-455e-92d6-d3c063103c4b)

![Image](https://github.com/user-attachments/assets/185abe1d-217d-4650-ade3-260016a489a0)

**Comment by RVFET** [comment]
I messed around a bit and found a fix. Basically, re-setting the primary desktop to your desired monitor after downloading the extension fixes the issue. But initially, when just installed it always defaults to built-in monitor and as mentioned before, does not respect specified primary monitor setting.
