### ISSUE TITLE
I getting btn.child.menu is null when install

### ISSUE THREAD

**Issue by ViniciusQuatrin** [neuromorph/openbar#5]
I am on Arch Linux using Gnome 45.2, and when I try to use the extension, I receive the following error:

![image](https://github.com/neuromorph/openbar/assets/104473428/cb0256d7-0f6b-45d0-a954-0ee560e411f7)

 I have other extensions that customize the top bar. They may affect it, but I don't think so

**Comment by neuromorph** [comment]
Yes, it does look like extension interference. Standard Gnome would have the menu in btn.child but an extension could change the layout of widgets. Please list the extensions you have enabled.
It would be very helpful if you try disabling all other extensions and restart Gnome (logout/login) and install/enable Open Bar. If it works then it confirms that some extension is interfering. Next, you can enable other extensions one by one to see what causes it to fail.
Once an interfering extension is identified, I can look into it to figure out how to to make it compatible.

So far, it should now work with Blur my shell, Just perfection (bottom pos needs some work), Expandable notifications and Quick Settings Audio Panel. 

Thanks for reporting the issue, let's figure out and fix it.

**Comment by ZeroSiks** [comment]
I am having the same issue on Fedora 38 with Gnome 44.7.
![image](https://github.com/neuromorph/openbar/assets/28683521/234b0877-2b7c-40d2-9488-4c609cdc466d)

Tried disabling all extensions but still get the error when installing.

**Comment by neuromorph** [comment]
Can you please run the following command in a terminal and then install the extension? The journal will show more detailed error message, please paste that here. Thanks.
`journalctl /usr/bin/{gjs,gnome-shell} -fo cat
`

**Comment by ViniciusQuatrin** [comment]
I found out that when the Arc Menu extension is disabled, it works properly. It's great if both extensions are compatible, so it works with the Arc Menu. However, when I disable it, open the 'Open Bar' extension, and enable it again, there is an issue, and it doesn't work on startup that way

**Comment by ZeroSiks** [comment]
I dont use Arc Menu so unfortunately that doesn't help me.

Here's the output from journalctl
<details><summary>Logs</summary>
<p>

yle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS LOG: Characters Application exiting
Can't update stage views actor <unnamed>[<ClutterActor>:0x5628a6b1cf60] is on because it needs an allocation.
JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: shown: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:273:22
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_showDone@resource:///org/gnome/shell/ui/overview.js:578:18
_animateVisible/<@resource:///org/gnome/shell/ui/overview.js:570:60
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:750:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

Received error from D-Bus search provider org.gnome.Boxes.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Boxes.SearchProvider without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Theme parser error: gtk.css:5628:3-9: No property named "height"
JS LOG: Characters Application started
Received error from D-Bus search provider org.gnome.Boxes.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Boxes.SearchProvider without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Received error from D-Bus search provider org.gnome.Boxes.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Boxes.SearchProvider without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: Exception in callback for signal: hidden: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
connect/<.id<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:45:65
_callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
_changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
_hideDone@resource:///org/gnome/shell/ui/overview.js:641:18
_animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
onStopped@resource:///org/gnome/shell/ui/overviewControls.js:771:21
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:151:22
_easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:317:60

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
updatePanelStyle/this.updateTimeoutId<@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:280:22
setTimeout/source<@resource:///org/gnome/gjs/modules/esm/_timers.js:72:9

JS ERROR: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.j┬─[raish@fedora:~]─[09:08:07 PM]
╰─>$ journalctl /usr/bin/{gjs,gnome-shell} -fo cat
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
JS ERROR: Extension openbar@neuromorph: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
enable@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:623:14
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:196:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:398:32
async*_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:294:35
Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:130:41

meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
JS ERROR: Extension openbar@neuromorph: TypeError: btn.child is undefined
resetStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:100:24
updatePanelStyle@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:347:14
enable@/home/raish/.local/share/gnome-shell/extensions/openbar@neuromorph/extension.js:623:14
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:196:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:398:32
async*_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:294:35
Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:130:41


</p>
</details>

**Comment by neuromorph** [comment]
@ViniciusQuatrin 
Thank you for the update. I checked and yes, there is issue with Arc Menu. I can do quick patch to avoid the error so that both extension can be enabled without error. However, the menu styles will not be applied to the Arc Menu menu by this since they are using custom layout for widgets within Arc Menu that is not captured by Open Bar. To make it fully compatible, Open Bar needs to scan through their layout and apply styles to all widgets. Turns out they have a ton of different layouts :eyes:  and large codebase so it will take a while to scour through it. I might try to see if they can help with it.
I will update here about the quick patch so you can start using both in the meanwhile.

@ZeroSiks 
Your issue is something else. Thanks for the log. I will try to replicate with Gnome 44 /Fedora 38 and get back.

**Comment by neuromorph** [comment]
OK, I have the quick patches up for both these issues. Please run indicated command below in a terminal to download and apply the patch. Both commands contain the same patches for both issues but one is for Gnome <45 and other for 45 due to different code bases.  Apply the correct patch and restart Gnome.
Note: as mentioned earlier, Arc Menu's menu will not get the Open Bar styles (yet).

@ViniciusQuatrin Run below Gnome 45 specific command:
 `cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/main/extension_v7patch.js; cat extension_v7patch.js > extension.js; rm extension_v7patch.js; cd`

@ZeroSiks Run below Gnome <45 command:
`cd ~/.local/share/gnome-shell/extensions/openbar@neuromorph/; curl -LJO https://raw.githubusercontent.com/neuromorph/openbar/g42-44/extension_v6patch.js; cat extension_v6patch.js > extension.js; rm extension_v6patch.js; cd`

Let me know how it goes.

**Comment by ViniciusQuatrin** [comment]
That's works perfectly! Thank you! Appreciate it

**Comment by neuromorph** [comment]
ViniciusQuatrin,
I have updated the patch for ArcMenu to apply the background styles to ArcMenu menu. For foreground, hover, active colors, they need to be set from the ArcMenu settings (as it tends to override). You can repeat the same command to get updated patch. This should now make the ArcMenu menu to be similarly styled as rest of the panel menus.

ZeroSiks,
I was not able to reproduce your issue on Gnome 44/Fedora 38 in a VM but the earlier patch should fix it anyway. I will wait to hear from you.

**Comment by ZeroSiks** [comment]
The patch worked perfectly. Installed and up and running with the extension. Thank you.

On a side note, I'm noticing some jank on the background colour alpha. Sometimes the bar is transparent but when I go to gnome overview and back its a solid fill and I can no longer see my wallpaper through the bar. Most definitely not related to this issue but thought it was worth mentioning.

**Comment by neuromorph** [comment]
The patches have been included in updates, versions v8 and v9 (Gnome 45).
